sonar.projectKey=jiangxincode_DingooEmu
sonar.projectName=DingooEmu
sonar.organization=jiangxincode-github

sonar.sources=crates
sonar.exclusions=**/target/**
sonar.sourceEncoding=UTF-8

sonar.rust.cobertura.reportPaths=coverage/cobertura.xml
